### ISSUE TITLE
How to test Maestro cards

### ISSUE THREAD

**Issue by crebuh** [Mangopay/cardregistration-js-kit#10]
Hi,

i've got a problem testing Maestro Cards. For example when i use the data from the test payment page:

N°: 3012340000000000
Expiry: Any date in the future
CSC: not required

I always got the following error:

Uncaught TypeError: Cannot read property 'length' of undefined

Stacke Trace:
mangoPay._validation._cvvValidator._validate	@	mangopay-kit.js:268
mangoPay.cardRegistration._validateCardData	@	mangopay-kit.js:90
mangoPay.cardRegistration.registerCard	@	mangopay-kit.js:57
registerCard	@	mangopay.js:28
_.mixin._.(anonymous function)	@	underscore.js:1178
(anonymous function)	@	confirm.js:231

This happens when I dont use a CSC (as described in the documentation). When i use a CSC like e.g. 123 then i got the following result:

{
ResultCode: "105204",
ResultMessage: "CVV_FORMAT_ERROR"
}

Does anybody has same problems?

**Comment by hobailey** [comment]
Hey @crebuh, sorry to hear you're having troubles. Are you definitly using the latest version of the kit? I'm pretty sure https://github.com/Mangopay/cardregistration-js-kit/commit/789999ab98be6a7bda1749269bd5c4464a13cdc2 fixed this problem.

**Comment by hobailey** [comment]
Also, you are definitely updateing the CardType to MAESTRO in this line: https://github.com/Mangopay/cardregistration-js-kit/blob/master/demo/index.php#L31

**Comment by crebuh** [comment]
@hobailey 

thx for the response. I updated to the latest version now the validator error message is gone.

Regarding the type of card I'm using this plugin (https://github.com/christemple/detect-card-js) to detect the card type in the background.

It is weird for the example number from Mangopay: 3012340000000000 it always tells me that it is a Diners-Card?

When i use another example number for Maestro like: 6759649826438453

it works ;)

**Comment by hobailey** [comment]
@crebuh yep, our PSP doesn't use the right BINs with their test cards unfortunately - it's on our list to sort out :-)

**Comment by rik** [comment]
FYI, we've seen the same issue with another library https://github.com/braintree/credit-card-type/issues/20

**Comment by hobailey** [comment]
Hi @rik, I confirm this is an issue with the test payment cards we use as the BINs are indeed inaccurate.
