### ISSUE TITLE
Card type missing in the demo

### ISSUE THREAD

**Issue by tildedash** [Mangopay/cardregistration-js-kit#11]
Hello,

The card type is missing in the demo and without this field the registration failed (for a 3 digits CVV).

Regards

**Comment by hobailey** [comment]
Hi @tildedash, 
I'm not sure to have understood your query - the CardType is given here: https://github.com/Mangopay/cardregistration-js-kit/blob/master/demo/index.php#L31
If you specify MAESTRO, you'll then not be required to supply a CVV.

**Comment by tildedash** [comment]
Yes, I'm talking about the HTML field that the JS try to retrieve here : https://github.com/Mangopay/cardregistration-js-kit/blob/master/demo/index.php#L92 

So cardData.cardType stays empty and _cvvValidator.validate return false : https://github.com/Mangopay/cardregistration-js-kit/blob/master/kit/mangopay-kit.js#L267

Did I miss something ?

**Comment by hobailey** [comment]
You're absolutely rightly - sorry about the confusion. I've just corrected that with https://github.com/Mangopay/cardregistration-js-kit/commit/09f93fe24959a38d6aecca1d4172edb5d916398a :-)
