### ISSUE TITLE
Cant post on https://homologation-webpayment.payline.com/webpayment/getToken  for card registration after a few payments

### ISSUE THREAD

**Issue by davidgeismar** [Mangopay/cardregistration-js-kit#13]
After a couple of successfull payments (usually two), I always get an error when trying to process a new payment at the card Registration state. 
I get this error : 

POST https://homologation-webpayment.payline.com/webpayment/getToken net::ERR_SSL_VERSION_OR_CIPHER_MISMATCH

the console is showing me error on line 510 of

https://github.com/Mangopay/cardregistration-js-kit/blob/master/kit/mangopay-kit.js#L510 when trying to tokenizeCard : https://github.com/Mangopay/cardregistration-js-kit/blob/master/kit/mangopay-kit.js#L107

**Comment by GuiminZHOU** [comment]
hi, in which environment it happens? prod or dev?

**Comment by GuiminZHOU** [comment]
me, i got the same error this morning,
Normally, this error would be from the browser. Me, i got the error on Chrome and no error on Firefox, and after update Chrome, it's ok

**Comment by davidgeismar** [comment]
It happens in dev, I havent try it out in prod mode

**Comment by hobailey** [comment]
Hey everyone, this is a problem of our PSP with Chrome only. We're in discussions with them to resolve it, but we don't yet have a fix date I'm afraid. 
I've just created a known issue if you want to follow updates over there: https://github.com/Mangopay/mangopay/issues/8
