### ISSUE TITLE
Will it be published on npm?

### ISSUE THREAD

**Issue by Guymestef** [Mangopay/cardregistration-js-kit#18]
Is it planned to publish this kit on npm? Or the only way to get it, is to download it manually?

FYI, if I try to install it directly with NPM from github, with the command:
npm i Mangopay/cardregistration-js-kit

The result is a fatal error:
fatal: no submodule mapping found in .gitmodules for path 'demo/mangopay2-php-sdk'

**Comment by hobailey** [comment]
Hi @Guymestef, thanks for the feedback. I've just deployed it to [npm](https://www.npmjs.com/package/mangopay-cardregistration-js-kit) so let me know if that hasn't resolved your problems :-)
