### ISSUE TITLE
Bad request on card registration

### ISSUE THREAD

**Issue by Sashkan** [Mangopay/cardregistration-js-kit#21]
I've been trying to registrate a card using the js kit. Everytime I do so, I get the same error message : 
```
https://api.sandbox.mangopay.com/v2/krawdsas/CardRegistrations/14185787 400 (Bad Request)
```
The card parameters look good to me:

```JS
Object {cardRegistrationURL: "https://homologation-webpayment.payline.com/webpayment/getToken", preregistrationData: "XBDYiG8w9PrylPS01KmupfYfhYAUBESyLlYyW3-jDvbjUUJout9NCj8o5ZLGcFLLS4wCy-yiraxeE65tmxOe8A", accessKey: "1X0m87dmM2LiwFgxPLBJ", Id: "14185787"}
Object {cardNumber: "3569990000000157", cardExpirationDate: "1218", cardCvx: "123", cardType: "CB_VISA_MASTERCARD"}
```

Did I miss something ?

**Comment by hobailey** [comment]
Hey @Sashkan, I expect it's probably related to an incident we're having at the moment: http://status.mangopay.com/incidents/9ld01jxgvhxj

We're working on resolving this right now, and it's not infact systematic. Please do let me know if you're still having the problems this evening and at what time and we'll take a closer look :-)
