### ISSUE TITLE
Payline errors not handled

### ISSUE THREAD

**Issue by lowwa132** [Mangopay/cardregistration-js-kit#22]
In case of error with Payline calls (for example 02631 Delay exceeded), errorCallback is not called and a call to MangoPay API is done anyway. Which results in my case in a very generic error "404", because the URL called is https://api.sandbox.mangopay.com/v2.01/myid/CardRegistrations/undefined

In _tokenizeCard method: 
```javascript
// Something wrong, no data came back from Payline
if (data === null) {
    errorCallback({
        "xmlhttp": xmlhttp,
        "ResultCode": "001599", 
        "ResultMessage": "Token processing error"
    });
    return;
}
```

Should be replaced by something like this:
```javascript
// Got error code from Payline
if (data !== null && data.indexOf("errorCode=") === 0) {
    errorCallback({
        "xmlhttp": xmlhttp,
        "ResultCode": data.replace("errorCode=", ""), 
        "ResultMessage": "Token processing error"
    });
    return;
} elseif(data === null || data.indexOf("data=") !== 0) {
    errorCallback({
        "xmlhttp": xmlhttp,
        "ResultCode": "001599", 
        "ResultMessage": "Token processing error"
    });
    return;
}
```

**Comment by lowwa132** [comment]
The card registration Id was missing, this is why I got "undefined" and 404 answser, but the general idea is the same, Payline errors are ignored.

**Comment by hobailey** [comment]
Great plan - thanks for the info/idea. I've just implented this with 918275588d44bd5de0cbc0a5ac1fb04682accddc :-)
