### ISSUE TITLE
Cors error from React Native App

### ISSUE THREAD

**Issue by abeauvois** [Mangopay/cardregistration-js-kit#24]
Getting a ResultCode 009999 with following code from React Native App:

```
      MP.cardRegistration.init({
        cardRegistrationURL: response.CardRegistrationURL,
        preregistrationData: response.PreregistrationData,
        accessKey: response.AccessKey,
        Id: response.Id
      });

      var cardData = {
        cardNumber: "4706750000000017",
        cardExpirationDate: "0317",
        cardCvx: "123",
        cardType: "CB_VISA_MASTERCARD"
      };

      MP.cardRegistration.registerCard(
        cardData,
        function(res) {
            // Success, you can use res.CardId now that points to registered card
            console.log(res)
        },
        function(res) {
          console.log(res)
            // Handle error, see res.ResultCode and res.ResultMessage
        }
      );
```

Also I  use the same headers for all requests:

```
      headers : {
        'Content-Type' : 'application/json; charset=utf-8',
        'Authorization': `Basic ${hash}`
      },

```
I've also tried to POST via Axios lib but I get a 09101 error (these errors only happen with this request)
Any way to solve or workaround this issue?

See attached IMG with response from PreRegistrationData request.

**Comment by hobailey** [comment]
Hey @abeauvois - you talk about an "attached IMG" but I don't see it - could you try uploading it again please?

**Comment by abeauvois** [comment]
Hi Hugo,

here is the devTool screenshot.

Alexandre

**Comment by hobailey** [comment]
Still no screenshot I'm afraid :-/

**Comment by abeauvois** [comment]
Curious because it was sent with attachment on my side.

Is it attached this time ?

---------- Forwarded message ----------
From: Alexandre Beauvois <abeauvois@gmail.com>
Date: Thu, Aug 4, 2016 at 6:39 PM
Subject: Re: [Mangopay/cardregistration-js-kit] Cors error from React
Native App (#24)
To: Mangopay/cardregistration-js-kit <
reply@reply.github.com
>
Cc: Mangopay/cardregistration-js-kit <
cardregistration-js-kit@noreply.github.com>, Mention <
mention@noreply.github.com>


Hi Hugo,

here is the devTool screenshot.

Alexandre

**Comment by hobailey** [comment]
No - please can you use the Github interface instead of sending it via email. Or alternatively email it to support@mangopay.com

**Comment by abeauvois** [comment]
Here it is:

<img width="1053" alt="screen shot 2016-08-03 at 21 02 46" src="https://cloud.githubusercontent.com/assets/309368/17434282/dc25aade-5b09-11e6-90d6-b916cbb252f5.png">

**Comment by hobailey** [comment]
OK, thank you. And could you confirm whether it happens during the POST creation of the card registration, or the later PUT update with the `RegistrationData`?

**Comment by abeauvois** [comment]
After I've created correctly the cardregistration and got the AccessKey and so on. 
When I send the MP.cardRegistration.registerCard with CardData, I get the error.

**Comment by hobailey** [comment]
OK, so the 2nd step (POSTing the data to the `CardRegistrationURL`) works correctly, and you receive back the "data=xxxxxx"?

**Comment by abeauvois** [comment]
Here is the request that fails: 

```
      const formData = {
        data: response.PreregistrationData,
        accessKeyRef: response.AccessKey,
        cardNumber: "4706750000000017", //cardNumber)
        cardExpirationDate: "0217", //cardExpirationDate)
        cardCvx: "123", //cardCvx)
      }
      
      return this.request('post', {url: response.CardRegistrationURL}, formData)
```

**Comment by hobailey** [comment]
Hi @abeauvois, coming back to this, it seems that our [check](https://github.com/Mangopay/cardregistration-js-kit/blob/master/kit/mangopay-kit.js#L586) for CORS support is incorrectly failing for React Native app (because it's based on a browser parameter which doesn't exist for React). 
>The security model for XMLHttpRequest is different than on web as there is no concept of CORS in native apps.

([Source](https://facebook.github.io/react-native/docs/network.html))

We're going to look into this to see if there is a way to detect React apps, and therefore better handle this.

**Comment by abeauvois** [comment]
sounds good, I'm sure this will help many future react-native developers, thanks for your efficient support.

**Comment by willmcneilly** [comment]
I came across the same problem and have dealt with it like this:

```javascript
corsSupport: function() {

    // Test if runtime is React Native
    if (window.navigator.product === 'ReactNative') {
        return true;
    }

    // IE 10 and above, Firefox, Chrome, Opera etc.
    if ("withCredentials" in new XMLHttpRequest()) {
        return true;
    }

    // IE 8 and IE 9
    if (window.XDomainRequest) {
        return true;
    }

    return false;

}

```

`window.navigator.product` will return 'Gecko' for all other browsers. One disadvantage of this is that the product property is deprecated, so I'm not sure how long ReactNative will support it for.

**Comment by hobailey** [comment]
Thanks @willmcneilly very much for the suggestion - that seems a very sensible approach. 

We've discussed internally the fact that its deprecated, and they (the React Native team) added this `navigator.product` property specifically to make it possible to detect React Native run time in 3rd party JS libraries (like in this case) as discussed [here](https://github.com/facebook/react-native/issues/1331) and added [here](https://github.com/facebook/react-native/pull/4083). 

The other solution would be to remove the CORS check altogether and let it fail if it’s really not supported. With the legacy browser share dropping every year, perhaps we don’t need to try to detect the lack of CORS support in advance (and risking a false alert). The check is there only to give a specific error code. If we remove the check, the call will fail anyway with some less clear error message but only for very old browsers.

**Comment by ignivalancy** [comment]
Mangopay React and React Native First JS Client library with card registration workflow.
https://www.npmjs.com/package/mangopay-client-react
