### ISSUE TITLE
1.1.0 is not tagged

### ISSUE THREAD

**Issue by AntoineLemaire** [Mangopay/cardregistration-js-kit#25]
Hello, 
Is it possible to tag 1.1.0 to easly get it with bower without use commit hash?

**Comment by hobailey** [comment]
Hey, can I ask why you specifically want that version, as opposed to the latest version which is 1.1.1?

**Comment by AntoineLemaire** [comment]
You're right, I didn't saw 1.1.1! But both are not tagged on github and I didn't notice that bower use only `package.json` to find list of versions.

     "mangopay-cardregistration-js-kit": "~1.0"

were not working but 

     "mangopay-cardregistration-js-kit": "~1.1"

yes...

Sorry for lost time!

**Comment by hobailey** [comment]
No worries, thanks for updating us!
