### ISSUE TITLE
Availability on CLJSJS

### ISSUE THREAD

**Issue by teawaterwire** [Mangopay/cardregistration-js-kit#26]
Hi,

Any plan to make it available on [CLJSJS](http://cljsjs.github.io/) for ClojureScript users?

Thanks 👍

**Comment by hobailey** [comment]
Hey @teawaterwire, thanks for the idea - this isn't something we've used before - do you think you'd be able to prepare a PR with the required changes?

**Comment by teawaterwire** [comment]
If I end up integrating MangoPay into my app I'll try and do it at the same time 💃

**Comment by hobailey** [comment]
Ok, that would be great, thank you :-)

**Comment by hobailey** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Add kit to CLJS.js](https://trello.com/c/OVZtwaCy/102-add-kit-to-cljs-js)
