### ISSUE TITLE
Validation isn't passed for  3ds testing cards

### ISSUE THREAD

**Issue by EvgeniyDubovoy** [Mangopay/cardregistration-js-kit#29]
I get 105204(CVV_FORMAT_ERROR) error, when I try to add one of 3ds testing cards (3569990000000132, 3569990000000157, 3012340000000000, 3012349999999999) 

The error occures in this function:

_validate: function(cvv, cardType) {

               if(cardType === "MAESTRO") {
                   return true;
               }
               cvv = cvv ? cvv.trim() : "";
               cardType = cardType ? cardType.trim() : "";

               // CVV is 3 to 4 digits for AMEX cards and 3 digits for all other cards
               if (mangoPay._validation._helpers._validateNumericOnly(cvv) === true) {
                    if (cardType === "AMEX" && (cvv.length === 3 || cvv.length === 4)) {
                        return true;
                    }
                    if (cardType === "CB_VISA_MASTERCARD" && cvv.length === 3) {
                        return true;
                    }
               }

               // Invalid format
               return {
                   "ResultCode": "105204",
                   "ResultMessage": "CVV_FORMAT_ERROR"
               };

            }

**Comment by hobailey** [comment]
What CVV are you using? i just registered 3569990000000132 / 1017 / 123 in sandbox with no problem :-/

**Comment by EvgeniyDubovoy** [comment]
It seems that we don't correctly determine the card type. Tell me please, how I can determine the card type by card number?

**Comment by hobailey** [comment]
Ah, so you're automatically detecting the `CardType` from the first 6 numbers of the card? Unfortunatley the BIN info for the cards in sandbox do not match the real `CardType` that they carry.

**Comment by EvgeniyDubovoy** [comment]
Ok, thanks. Tell me please, what constans we need to use for card types. As far as I understand, constant CB_VISA_MASTERCARD is used  for Visa and Mastercard. Am I right? What constants for other card types?

**Comment by hobailey** [comment]
If you hover over "CardType" in [the docs](https://docs.mangopay.com/endpoints/v2.01/cards#e178_create-a-card-registration), you'll see the diferent possible options.

**Comment by EvgeniyDubovoy** [comment]
Thank you for help.
