### ISSUE TITLE
would be nice to install with bower

### ISSUE THREAD

**Issue by PedroEsperanca** [MangoPay/cardregistration-js-kit#3]
http://bower.io/docs/creating-packages/

**Comment by javiercr** [comment]
+1 for wrapping this into a bower package. @jdiprizio works but doesn't allow to use things like [bower-main-files](https://github.com/ck86/main-bower-files) as there are no "main" files defined.

**Comment by hobailey** [comment]
Hi everyone,
Thanks for the idea and sorry for the delay getting back to you. I'm not too familiar with creating packages with Bower - has anyone done this before and happy to make a pull request?
