### ISSUE TITLE
Issue with chrome 60

### ISSUE THREAD

**Issue by cyboolo** [Mangopay/cardregistration-js-kit#39]
The card registration kit is not working anymore with chrome 60.

Everything was working ok before that version.

Now when i try to register a card I get:

XMLHttpRequest cannot load https://homologation-webpayment.payline.com/webpayment/getToken. Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource.

and: ResultCode: 001596, ResultMessage: An HTTP request was blocked by the User's computer (probably due to an antivirus)

I don't have antivirus and it was working fine before.

If someone can help please. Or am I the only one to have this issue?

**Comment by scorring** [comment]
Same issue here. Access-Control-Allow-Origin header missing on card homologation endpoint (POST on https://homologation-webpayment.payline.com/webpayment/getToken)

**Comment by mangomaxoasis** [comment]
Hi @scorring @cyboolo 
I'm closing this issue, please feel free to comment in 
https://github.com/Mangopay/cardregistration-js-kit/issues/46
We are currently working on the cardkit, we'll update the other issue 
Thank you,
Max
