### ISSUE TITLE
Browser support without CORS

### ISSUE THREAD

**Issue by javiercr** [MangoPay/cardregistration-js-kit#4]
Hi,

The current JS kit does not support browsers without CORS support. From the readme:

> The library makes cross-origin Ajax calls (CORS) to get the card token and handle card registration with MangoPay API. Therefore it requires a browser that supports CORS. The kit does not currently work in Internet Explorer 6, 7 & 8 and Opera Mini (**fix due in November 2014**).

Is there any progress on this?

Thanks.

**Comment by hobailey** [comment]
Hi @javiercr, sorry for the lack of updates. IE8 is now supported but I've just checked and IE6+7 have a different error, so I'll let you know via this thread when thats improved (if it is indeed possible to fix).

**Comment by javiercr** [comment]
Great, thanks for the update @hobailey!

**Comment by hobailey** [comment]
Hi @javiercr, I've just been told by our tech team that the annoucement in the readme was misleading - we never infact planned to support IE6/7 given the incredibly low usage (and complexity of doing so) but IE8 is fine.
