### ISSUE TITLE
Expiry date format is always wrong?

### ISSUE THREAD

**Issue by Doko-Demo-Doa** [Mangopay/cardregistration-js-kit#41]
As far as I know, we had to use Unix epoch timestamp when creating card registration call. But I always get error 105203 when trying to do so.

```
var cardData = {
  cardNumber: '4706750000000009',
  cardExpirationDate: '1595293261', // For 2020
  cardCvx: '343',
  cardType: 'Visa',
};
```

Any idea?

**Comment by hobailey** [comment]
The expiry date date here is not epoch but MMYY infact :-)
