### ISSUE TITLE
Register cards other than CB_VISA_MASTERCARD

### ISSUE THREAD

**Issue by foramkumarparekh** [Mangopay/cardregistration-js-kit#44]
Hi, I am aware of how to register Visa/ master card. Also, I guess I can use the same way for Diners,
but for the rest, MASTERPASS, MAESTRO, P24, IDEAL, BCMC, PAYLIB, how can I create card registration?

I am using mangopay2-nodejs-sdk kit in the backend.

**Comment by mickaelpois** [comment]
Hi @foramkumarparekh,

For MAESTRO and BCMC, you can easily register a card the same way you've done with VISA/Mastercard.
You can find some testing informations here: https://docs.mangopay.com/guide/testing-payments (be very careful with password required when doing a payin, which are different from VISA/Mastercard!)

For MASTERPASS, P24, IDEAL and PAYLIB, there is no Card registration (as registration is "done" on these partners side) ans so no need to use this kit. You just have to use nodejs SDK only and process a Payin Web (docs here: https://docs.mangopay.com/endpoints/v2.01/payins#e269_create-a-card-web-payin) where you can set any card type we support.

Let me know if everything is clear for you :)

Mickaël

**Comment by foramkumarparekh** [comment]
For MASTERPASS, P24, IDEAL and PAYLIB, is direct payin possible? and how?

**Comment by mickaelpois** [comment]
No, you can't, just because all these methods of payment require a validation through a web interface.

**Comment by foramkumarparekh** [comment]
Hi,
can you just share the object for registering DINERS, MAESTRO and BCMC as, VISA  has expiry date and csv while this CARD-TYPES have passwords.
