### ISSUE TITLE
Error: Token processing error occuring

### ISSUE THREAD

**Issue by catuss-a** [Mangopay/cardregistration-js-kit#45]
Hi,
We have been using this Kit for quite a while and it looks to work pretty much well so we'd like to thank you for that firstable.

However we recently noticed that some of our users were getting returned from the call to `mangoPay.cardRegistration.registerCard(cardRegistrationData)` a "Token processing error".

We have re-checked our code client/sever side and we cannot really find something that we process wrongly (we use this js-kit coupled to the mangopay ruby gem).
We are now wondering in which cases exactly the MangoPay API throws that error ? The documentation just inform us that: `The token has not been created as there was a problem - check that you sent all the correct parameters.` but not much more.

May you give us more informations about that error ?

PS: This error happens apparently only after a first token request, then the 2nd one, without any page reloading, results to a successful card registration considering that the credit card details are correct.

Thanks for your time

**Comment by mangomaxoasis** [comment]
Hi @catuss-a 
This errors seems to occur on the card tokenisation step, it may have been an localised issue with the tokenisation server.
We have not been able to reproduce the issue.
Please contact us if the issue recurs.
Best,
Max
