### ISSUE TITLE
Callback pour la function mangoPay.cardRegistration.registerCard

### ISSUE THREAD

**Issue by mijebari** [Mangopay/cardregistration-js-kit#47]
Bonjour,

je suis incapable de savoir si l’exécution de la fonction mangoPay.cardRegistration.registerCard est terminé ou pas vu qu'il n'y a pas de callback a cette fonction.

mon besoin est de pouvoir exécuté une autre fonction des réceptions du CardId.

Merci pour votre aide.

**Comment by VincentMaret** [comment]
Il y a bien deux callback à passer en paramètre de la fonction, la 1ère pour le succès et la deuxième pour l'erreur comme indiqué dans la doc. Tu peux aussi wraper la fonction dans une promise pour éviter de bosser avec des callbacks.

**Comment by ilyasjebari** [comment]
Merci
