### ISSUE TITLE
Can we use mangoPay.cardRegistration.registerCard with Angular or Java api

### ISSUE THREAD

**Issue by maznag** [Mangopay/cardregistration-js-kit#49]
I want to integrate MangoPay to my application that I develop using Angular Framework and Java / Spring.

Do you have another way to use the mangoPay.cardRegistration.registerCard method using either Angular without passing through your JavaScript / JQuery code, or directly using the server-side Java API. This function doesn't exists in you api JAVA mangopay2-java-sdk

Thanks

**Comment by Riwak** [comment]
Hello @maznag, 

Not for the moment, but there is some useful ressources on our docs here : https://docs.mangopay.com/endpoints/v2.01/cards#e178_create-a-card-registration

You have also a code example from the java sdk here : https://github.com/Mangopay/mangopay2-java-sdk/blob/master/src/test/java/com/mangopay/core/BaseTest.java (Line 647 to 690)

I stay available if needed

**Comment by maznag** [comment]
@Riwak thanks.

I already use your api documentation, it's useful. Now I can register new card from browser by adding a new service Angular to load directly your JS script from a public URL.
