### ISSUE TITLE
registerCard method does not comply with Registration Flow diagramm

### ISSUE THREAD

**Issue by theluk** [Mangopay/cardregistration-js-kit#56]
Hello,

following the [registration flow](https://docs.mangopay.com/endpoints/v2.01/cards#e177_the-card-registration-object) it seams as this js kit does not follow the steps as it should.

Mainly it is taking over the steps 7 as it should, but also 8 and 9. 

Currently the `_tokenizeToken` is the actual function (step 7) that should be used (only) and steps 8 and 9 should be done on the server. 

While we can do that by just calling the function, it should be rewritten in a way, that it is not marked as private and also so that it foster the flow.

**Comment by mangomaxoasis** [comment]
Hi @theluk,
I agree the workflow isn't ideal, we are reworking these assets over the next quarter 
I'll see if we can fix something here.
