### ISSUE TITLE
How to make this work on SSR framework ?

### ISSUE THREAD

**Issue by vasilvestre** [Mangopay/cardregistration-js-kit#59]
Using payment via SSR framework lead to a CORS error. How should we handle this ?

**Comment by jidefela-mgp** [comment]
Hello @vasilvestre  

Closing this issue as we're deprecating this SDK as of today (24-July). You should upgrade to the newest version of our [Vault SDK](https://mangopay.com/docs/sdk/vault-web), which provides the same functionality of card-registration.

Should you experience this issues with our new SDK, please don't hesitate to reach out to our team via [the Hub](https://hub.mangopay.com/).

Thanks!
