### ISSUE TITLE
Cant register card

### ISSUE THREAD

**Issue by davidgeismar** [MangoPay/cardregistration-js-kit#6]
Hey Ive been having problems registering my mangopay_user card : 
I keep getting a Token processing error Code : 001599. 
In Chrome console I can see the following error:
==> the JS Kitt is trying to send an AJAX POST request on the current URL im on apparently...

POST http://localhost:3000/tournaments/14/subscriptions/new 404 (Not Found)VM1929 mangopay-kit-e27868d9cf3fe01a73b96d6d899aabd0.js?body=1:507 mangoPay._networking._ajaxVM1929 mangopay-kit-e27868d9cf3fe01a73b96d6d899aabd0.js?body=1:110 mangoPay.cardRegistration._tokenizeCardVM1929 mangopay-kit-e27868d9cf3fe01a73b96d6d899aabd0.js?body=1:64 mangoPay.cardRegistration.registerCardnew:170 registerCardDemonew:100 onclick
<script type="text/javascript" >

function registerCardDemo() {

    var resultDiv = document.getElementById("result");
    resultDiv.innerHTML = "Vérification...";
    resultDiv.style.color = "black";

      // Card register data prepared on the server
    var cardRegisterData = {
        cardRegistrationURL: "<%= params[:card_registration_url] %>",
        preregistrationData: "<%= params[:preregistration_data] %>",
        accessKey: "<%= params[:access_key] %>",
        Id: "<%= params[:card_registration_id] %>"
    };

     // Card data collected from the user
    var cardData = {
         cardNumber: document.getElementById("card_number").value,
         cardExpirationDate: document.getElementById("card_expiration_date").value.replace('/',''),
         cardCvx: document.getElementById("card_cvx").value,
         cardType: document.getElementById("card_type").value
    };

// Set MangoPay API base URL and Client ID

    mangoPay.cardRegistration.baseURL = "<%= ENV['MANGOPAY_PRODUCTION'] == 'true' ? 'https://api.mangopay.com' : 'https://api.sandbox.mangopay.com' %>";
    mangoPay.cardRegistration.clientId = "<%= ENV['MANGOPAY_PRODUCTION'] == 'true' ? 'tennismatch' : 'davidgeismar' %>";

 // Initialize the CardRegistration Kit
    mangoPay.cardRegistration.init(cardRegisterData);

    // Register card
    mangoPay.cardRegistration.registerCard(cardData,
        function(res) {
            var message = 'Votre carte a été vérifiée ' + res.CardId + '.<br />';
            message += 'Le paiement est en cours';
            resultDiv.innerHTML = message;
            resultDiv.style.color = "green";
            $.ajax({
              type:"patch",
              dataType: "script",
              url: "<%=j user_path(current_user)%>",
              data:{user:{card_id: res.CardId}},
                          })
        },
        function(res) {
            var message = "Votre carte n'a pas été débitée.<br />";
            message += res.ResultMessage + '<br />' +' Code : ' + res.ResultCode ;
            resultDiv.innerHTML = message;
            resultDiv.style.color = "grey";
        }
    );
}

</script>

Has someone an idea about what's going on ?
thanks

**Comment by hobailey** [comment]
Hi there, could you share with us some code? I've just tested the code thats in the repo and its working fine :-) Have you modified the code at all?

**Comment by davidgeismar** [comment]
Ok sorry I solved the problem ! But now I have another one. When I register my testcard, I am trying to save the cardid Mangopay sends me into my database so once the card is registered, I am sending an ajax request : 
   $.ajax({
              type:"patch",
              dataType: "script",
              url: "<%=j user_path(current_user)%>",
              data:{user:{card_id: res.CardId}},
                          })
Unfortunately chrome console keeps sending me the following error:
PATCH http://localhost:3000/users/14 500 (Internal Server Error) which refers to the following line in jquery:
                                         // Do send the request
					// This may raise an exception which is actually
					// handled in jQuery.ajax (so no try/catch here)
					xhr.send( ( options.hasContent && options.data ) || null );

Here's my code 

<script type="text/javascript" >

function registerCardDemo() {

    var resultDiv = document.getElementById("result");
    resultDiv.innerHTML = "Vérification...";
    resultDiv.style.color = "black";

      // Card register data prepared on the server
    var cardRegisterData = {
        cardRegistrationURL: "<%= params[:card_registration_url] %>",
        preregistrationData: "<%= params[:preregistration_data] %>",
        accessKey: "<%= params[:access_key] %>",
        Id: "<%= params[:card_registration_id] %>"
    };

     // Card data collected from the user
    var cardData = {
         cardNumber: document.getElementById("card_number").value,
         cardExpirationDate: document.getElementById("card_expiration_date").value.replace('/',''),
         cardCvx: document.getElementById("card_cvx").value,
         cardType: document.getElementById("card_type").value
    };

// Set MangoPay API base URL and Client ID

    mangoPay.cardRegistration.baseURL = "<%= ENV['MANGOPAY_PRODUCTION'] == 'true' ? 'https://api.mangopay.com' : 'https://api.sandbox.mangopay.com' %>";
    mangoPay.cardRegistration.clientId = "<%= ENV['MANGOPAY_PRODUCTION'] == 'true' ? 'tennismatch' : 'davidgeismar' %>";

 // Initialize the CardRegistration Kit
    mangoPay.cardRegistration.init(cardRegisterData);

    // Register card
    mangoPay.cardRegistration.registerCard(cardData,
        function(res) {
            var message = 'Votre carte a été vérifiée ' + res.CardId + '.<br />';
            message += 'Le paiement est en cours';
            resultDiv.innerHTML = message;
            resultDiv.style.color = "green";
            $.ajax({
              type:"patch",
              dataType: "script",
              url: "<%=j user_path(current_user)%>",
              data:{user:{card_id: res.CardId}},
                          })
        },
        function(res) {
            var message = "Votre carte n'a pas été débitée.<br />";
            message += res.ResultMessage + '<br />' +' Code : ' + res.ResultCode ;
            resultDiv.innerHTML = message;
            resultDiv.style.color = "grey";
        }
    );
}

</script>

**Comment by hobailey** [comment]
It looks like this error 500 is on your side though and is nothing to do with our API? Ie when you do the the AJAX PATCH call, it's your local server replying with 500 it seems?

**Comment by davidgeismar** [comment]
YEah found the problem.. was trying to redirect an AJAX call. Thanks

**Comment by hobailey** [comment]
Great, thanks for the update :-)
