### ISSUE TITLE
Proper handling of web content filtering

### ISSUE THREAD

**Issue by outofrange-consulting** [Mangopay/cardregistration-js-kit#60]
Some of our customer are using our website from an entreprise network.
Those networks often have a Web Content Filtering policy, and sometimes the payline website is blocked.

Using the kit, the call to the payline website will be filtered, probably return a HTTP 200 page with HTML content (allowing the end user to see that the target page has been blocked), but usually not contain an 'errorCode' part.

The result is that the HTML content from the Web Content Filtering policy is sent to MangoPay API, producing a HTTP 500 response from your side.

If think some improvement could be the use of a regular expression, or at least a more strict error handling to ensure the process only continues if the payline response contains a valid registration data.

**Comment by jidefela-mgp** [comment]
Hello @outofrange-consulting 

We're deprecating this SDK as of today (24-July). You should upgrade to the newest version of our [Vault SDK](https://mangopay.com/docs/sdk/vault-web), which provides the same functionality of card-registration.

If you still experience the same issues with our new SDK, please reach out to our team via the [Hub](https://hub.mangopay.com/).

Thanks!
