### ISSUE TITLE
Find a better way to get the client ID

### ISSUE THREAD

**Issue by RobertAudi** [Mangopay/cardregistration-js-kit#8]
In the [demo](https://github.com/Mangopay/cardregistration-js-kit/blob/master/demo/index.php#L96-L97), the client ID is injected into the page directly. This is probably not very secure imho.

I looked around for alternatives, and it turns out that this is a pretty common problem on the web.

Putting the client ID in a cookie is definitely not a solution. And I am not confortable at all relying solely on SSL.

The best solution I can think of is to make a request to the server to retrieve the client ID. However, the request would have to be authenticated, otherwise, this solution is as brittle as the other ones.

There should be some kind of guideline to approach this problem, and ideally a solution that comes with the JS kit itself (and with the other API clients as well; I use the Ruby SDK).

**Comment by javiercr** [comment]
What's the problem with having the ClientID injected into the page? For most MangoPay users I bet the ClientID is just the name of the company, therefore even if you hide it, it's very easy to guess it. As long as the client_passphrase is secret (which it is) I personally don't see any security risk on this.

To my understanding, ClientID is just like a username, and the passphrase the password. Therefore only the passphrase needs to remain secret.

**Comment by RobertAudi** [comment]
You are right. I actually realized that after a while. I guess the term "Client ID" is a bit misleading since it usually a piece of information that is strongly advised not to share by other API providers.

Sorry about the confusion.

**Comment by hobailey** [comment]
Thanks @javiercr for the clarifications - you absolutely right, @RobertAudi you have nothing to worry about exposing this info :-)
